### ISSUE TITLE
Ships PreAlpha 4.2 bug

### ISSUE THREAD

**Issue by TheGamerRules** [mosemister/Ships-5-Bukkit-Version#10]
I don't know if you have caught this bug yet but here it is. If you hover above a move sign on a watership, it will go down in to the water, and if you click from the bottom of the move sign it will go up in the air and hover one block in the water, and you can't make it go down unless there's water under it.

**Comment by mosemister** [comment]
I had not seen that. However I understand the issue. It will be fixed in the next pre alpha. Thanks for putting this bug report on

**Comment by mosemister** [comment]
https://github.com/mosemister/Ships-2ndGen/commit/fdc5e897ae26bd66314c683ce588fe9e55a8ae23
This is now fixed
