### ISSUE TITLE
Ships Version 6

### ISSUE THREAD

**Issue by Bossbirdyman51** [mosemister/Ships-5-Bukkit-Version#11]
Hi,
I like your plugin, and i want to use AutoPilot, can you upload ships version 6 for test ?
Thanks, sorry for my language.

**Comment by mosemister** [comment]
You can download the pre release version of Ships 6 [here](https://github.com/mosemister/Ships-2ndGen/releases). However AutoPilot in Ships 6 does not work correctly, it does work correctly and fully in Ships 5 that you can download [here](https://dev.bukkit.org/projects/ships/files).

I sadly do not have a release date for the next update, however I am hoping to release the next update soon

I have been working on uni work and have not had the time to work on ships in months. AutoPilot is not planned for the next release, you can see the next plans [here](https://dev.bukkit.org/projects/ships/pages/ships-6).
The autopilot bug that is currently in the code makes the whole ship disappear on movement. I belive this is to do with the movement code, however i will need to do some testing and fix the issue.

**Comment by Bossbirdyman51** [comment]
Okay, Sorry but if I wrote /ships autopilot Test X Y Z it's doesn't work, i use version 5.0.1.9 (MC 1.10.X).

**Comment by mosemister** [comment]
Is it enabled in the config?

**Comment by Bossbirdyman51** [comment]
Yes i have activate it but it's doesn't work with Ship ?

**Comment by Bossbirdyman51** [comment]
WaterShip

**Comment by mosemister** [comment]
Ah. Autopilot only works on air based ships, such as the airship, marsship, plane, etc

**Comment by Bossbirdyman51** [comment]
Are you french ? ;)

**Comment by mosemister** [comment]
Nope sorry. English

**Comment by Bossbirdyman51** [comment]
Okay, can i configure the speed of AirShip with AutoPilot ?

**Comment by mosemister** [comment]
Sorry. Ships 5 autopilot will only move at the speed of 1-2 due to how ships 5 autopilot works

**Comment by Bossbirdyman51** [comment]
And it's possible to change the speed ?

**Comment by mosemister** [comment]
Nope. Not in ships 5. It should be in ships 6

**Comment by Bossbirdyman51** [comment]
Hum you can't create a new .jar just for me for change the speed ? Please.

**Comment by mosemister** [comment]
Nope. The ships 5 algorithm for autopilot requires the ships autopilot speed to be 1-2. If i were to change the speed it would not work. Meaning i would need to recreate the whole autopilot code to make that work, due to my limited time i rather spend that time getting ships 6 to release with a configurable auto pilot

**Comment by Bossbirdyman51** [comment]
Okay, and you don't have a date for the version 6 of ships ?

**Comment by mosemister** [comment]
Sorry. 
Ships 6 has completely new code from the ground up. Meaning it will take a while to develope

**Comment by Bossbirdyman51** [comment]
Okay i understand thanks. It's possible to you to resolve bug with another plugin ? It's for https://dev.bukkit.org/projects/gates  I have this error : https://pastebin.com/uwZzBYQz
Sorry i know it's not your job but i lovely love this plugins ^^

**Comment by mosemister** [comment]
It is a problem where the plugin is requesting for the players health. However it looks like it is using a older version. This is something that is not your fault unless your using a much newer version of bukkit then what the plugin needs.

The way to fix this from the plugin side is to request a players health using the new way

double health = ((Damagable)player).getHealth();

Sorry i can not be anymore help then that

**Comment by Bossbirdyman51** [comment]
Okay, thank you very much !
