### ISSUE TITLE
Vessel Requires 0.0 of (any) wool

### ISSUE THREAD

**Issue by 1234fireball** [mosemister/Ships-5-Bukkit-Version#12]
I continue to get this with when trying to make larger ships! It just doesn't want to allow them to fly! https://pastebin.com/Vz63Y0uP is my set up for airship config where the problem is from.

**Comment by mosemister** [comment]
TakeAmount needs to be a whole number. 

It is likely that is causing a crash at the start. As for the message ignore the amount as that is wrong
