### ISSUE TITLE
Can't disable burner

### ISSUE THREAD

**Issue by Duvetyn** [mosemister/Ships-5-Bukkit-Version#13]
I can't disable burner in the config for airships. I've tried and it says disabled in the config, but in the [ships] information area, there's still 'Requires Burner: True"
      airship
      name

How can I fix this?

**Comment by mosemister** [comment]
Im assuming you are running Ships 6.0.0.0? If so make sure it is disabled in the VesselData file. By disabling it in just the config for the airship, it only affects the Ships that are created after the value was changed

**Comment by Duvetyn** [comment]
Right, I'll try that. Thank you

**Comment by mosemister** [comment]
Did it work?

**Comment by Duvetyn** [comment]
Sorry for the late reply, no it didn't. Even new vessels need burners, so
it wasn't the fault of the config.

**Comment by mosemister** [comment]
Sorry for my late reply. I found reasently that ship type data doesn't actually get read, however Vessel Data does. This has been fixed in the next release of Ships Alpha 2.0 so its just a matter of waiting for it. 

As mentioned before, you can disable the burner on a per vessel bases.

**Comment by Duvetyn** [comment]
Thanks for telling me.

**Comment by mosemister** [comment]
The alpha 2.0 release is now out. Give it a go and tell me how it is.

**Comment by mosemister** [comment]
Due to a lack of reports, i will close this issue.
