### ISSUE TITLE
Issue: console spam

### ISSUE THREAD

**Issue by shueja** [mosemister/Ships-5-Bukkit-Version#19]
[Sat, 17. Aug 2019 18:54:02 PDT INFO] ships:airship.starmansuper | airship.icanfly4
[Sat, 17. Aug 2019 18:54:02 PDT INFO] ships:airship.jankyship | airship.icanfly4
[Sat, 17. Aug 2019 18:54:02 PDT INFO] ships:airship.galleon | airship.icanfly4
[Sat, 17. Aug 2019 18:54:02 PDT INFO] ships:airship.woomy | airship.icanfly4

This message pops up in my console with various ship ids at the end of the lines. It seems to be caused by a Java for each loop logging each airship Id against the target one. It’s not an error but you might want to check the code that finds a ship based on its id

**Comment by mosemister** [comment]
Yes I know where that issue is. Its when I was testing the clonable ship type on other shiptypes then the airship. It will be sorted.

**Comment by shueja** [comment]
Okay cool. Just checking

**Comment by mosemister** [comment]
Fixed in Alpha 2.2
