### ISSUE TITLE
Issue/Feature request: disable EOT when ship is unoccupied

### ISSUE THREAD

**Issue by shueja** [mosemister/Ships-5-Bukkit-Version#20]
I’ve lost several ships due to falling off the back while EOT was enabled. Can you please add a setting so that EOT is shut off when the captain leaves the ship or logs off? Alternatively provide a way for a captain to recover their ship after it has moved on its own from where they left it?

**Comment by mosemister** [comment]
Recovery is going to be a option, with autopilot already added (as in the command) however I believe the eot and autopilot conflict with one another. 

The other way of recovery is to use the teleport command that isnt added yet. 

I will add the ability to make it so the captain can automatically disable the eot and if the ship is empty.

**Comment by shueja** [comment]
Okay. Also since you mentioned it, will the teleport command teleport the captain to the ship ( easier to do given you know exactly where the license sign is) or vice versa?

**Comment by mosemister** [comment]
It will teleport the player to the ship, a known location on the ship (by default the players location when the licence sign is created)

**Comment by mosemister** [comment]
This is fixed with the EOT command

**Comment by shueja** [comment]
Okay cool. And since you mentioned autopilot, is it supposed to be functioning in the latest release?

**Comment by mosemister** [comment]
Autopilot hasnt been touched since prealpha 1.2, in that it would get closer but as soon as it needed to turn it would stop moving. So no not yet. It sadly hasnt been high on the priority

**Comment by shueja** [comment]
Ok no problem just checking before I make an issue about it
