### ISSUE TITLE
Issue: Kelp Detect

### ISSUE THREAD

**Issue by bradyyykennyy** [mosemister/Ships-5-Bukkit-Version#21]
Pretty self explanatory. When traveling in a boat, 1.14.4, any Kelp thats in the way of the boat will stop it from being able to move on. I've tried making kelp a material in the config to try and make it apart of the boat every time I run into on the ocean, but it's tedious. I feel the ship should be able to just run through plants like that.

**Comment by mosemister** [comment]
There is. Change the CollideType to IGNORE.
