### ISSUE TITLE
Water issues when airship lands and takes off from water

### ISSUE THREAD

**Issue by shueja** [mosemister/Ships-5-Bukkit-Version#22]
Specifically, I get craters in the ocean surface when my airship takes off from being partially below water level. I know this is Minecraft water mechanics trying to cope with structure movement but is there a way to stop these from happening?

**Comment by mosemister** [comment]
The airship was not designed to go into the water at all, I thought I made it almost impossible. I will see what I can do though

**Comment by shueja** [comment]
Oh ok. Is there a ship type that is able to land in water and also fly? For the record I set water as an IGNORE collidetype. I expected it would fill back in after the ship took off but it didn’t. Consider a world edit-style //fixwater limited to just the area under the ship.

**Comment by mosemister** [comment]
There is one planned for full release but its planned for a later alpha release

**Comment by mosemister** [comment]
This should be fixed in alpha 2.2. Ill leave this topic open until you agree it is fixed

**Comment by shueja** [comment]
This issue is fixed. Should I open a different one to talk about the issues with waterlogged blocks ?

**Comment by mosemister** [comment]
Yep
