### ISSUE TITLE
Land Vessels

### ISSUE THREAD

**Issue by test414EFF** [mosemister/Ships-5-Bukkit-Version#23]
I'm unsure if this plugin currently has any land-vehicle capabilities as I haven't had the chance to look super far into it, however according to the plugin description it seems as though you can only create vehicles that travel in/on water and in air. I would like to be able to create ships that I can drive on land with this plugin.

**Comment by mosemister** [comment]
The feature was requested a long time ago and sadly its much more difficult to do due to terrain. Its also not in my vision for ships. So sorry but I will nof add this feature.
