### ISSUE TITLE
Feature request: limited structure updating on ships

### ISSUE THREAD

**Issue by shueja** [mosemister/Ships-5-Bukkit-Version#24]
Is it possible to make the ships not automatically consider any adjacent material blocks part of the ship, but only update the structure when the player wants it to (sign click)?

**Comment by mosemister** [comment]
Thar feature is planned but not implemented yet as another feature like it needs to be added with it at the same time and its still in the design phase

**Comment by mosemister** [comment]
This feature is now in Ships 6.0.0.0 Alpha 2.3
