### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by MarcinWieczorek** [mosemister/Ships-5-Bukkit-Version#6]
Hi

What do you think about using maven?

**Comment by mosemister** [comment]
Currently I am focused on making the plugin. If i was going to use something like Maven, i would use Gradle due to the fact Maven doesn't like my computers (don't know why)

**Comment by MarcinWieczorek** [comment]
Maven does not like your computers? Interesting. It is your configuration probably. You just install maven and use it, what's the deal?

**Comment by mosemister** [comment]
It always crashed my Eclipse. Gradle doesn't. And i rather just use a single program

**Comment by MarcinWieczorek** [comment]
Use Intellij IDEA.

**Comment by mosemister** [comment]
Thanks for the request, but I rather stick to Eclipse due to the fact I don't need to download it every time I want to program at University

**Comment by MarcinWieczorek** [comment]
Keep your OS on a flash drive :)

**Comment by mosemister** [comment]
Bios is locked on uni computers and they will kicked me out if i open the computer up and remove the bios battery

**Comment by MarcinWieczorek** [comment]
So your excuse not to use Maven is being kicked outta the Uni for hacking their PCs.
Well, that's a shame. Learn the configuration of Eclipse and Maven. I would help you with the project, I wanted to check it out, compile and run on my server, but I don't have time to lose every time I want to set it up.

**Comment by mosemister** [comment]
Just saying - eclipse allows you to download and compile without Maven. Not only that but i provide already compiled versions of the plugin.

**Comment by MarcinWieczorek** [comment]
I prefer freedom over binaries. Eclipse does not allow you to resolve dependencies without any idea what they are.

**Comment by mosemister** [comment]
Fair enough. I will not provide a Maven project right away. Maybe later but dont get your hopes up

**Comment by MarcinWieczorek** [comment]
I'd be happy to help.

**Comment by MarcinWieczorek** [comment]
Why not close this from a commit adding Maven support? This issue is unresolved.

**Comment by mosemister** [comment]
I know it is not resolved. But like i said, dont get your hopes up for a Maven version. There is a chance but not right away, when the time is right this will reopen

**Comment by MarcinWieczorek** [comment]
That's not how it works.
