### ISSUE TITLE
Ship requirements change on rotate

### ISSUE THREAD

**Issue by WolfieWaffle** [mosemister/Ships-5-Bukkit-Version#7]
I am using the prealpha-2 build (I assumed this was the most recent one). When I create a ship and rotate it using the wheel, the wheel sign does not turn correctly and the ship stops working. Specifically, it says that I need more wool blocks, even though before rotating it was fine.

Sorry if you are aware of this issue and this is an old version, I assumed since it was downloadable that it was available to report bugs on.

**Comment by mosemister** [comment]
There seemed to be a huge issue where the block detection system doesnt work randomly, once it stops working then it will not work at all until you remove the ship then readd the ship. My guess is the bug you found is related to that. I will be taking a look at it in more detail a little later, however, at this point in time it is not a priority (but will be very soon).

P.S the latest at the point in time you sent the message was 3.0 (The latest is always just labelled as Ships.jar). A new update is being released right now however the bug should still consist so be warned

**Comment by WolfieWaffle** [comment]
Hm, thanks for the reply. I downloaded the Ships.jar just now, and it seems to have a different problem entirely. I keep creating new ships, but each one of them always has the bedrock collision thing on any attempt to move. I'm sure you are aware of the issue, but I just wanted to post it just in case. You are actually responding and debugging, so your doing better than Movecraft in my opinion. I'm going to make some feature request issues to see how feasible they are.

**Comment by mosemister** [comment]
I was not aware of that issue. Can i ask what Ship type(s) it was?

I will happily take requests, especially right now, I always have for Ships. 

I find it a lack of motivation for a plugin if you just develop for it and you don't take in the users interests and requests, so I will always reply and attempt to add features that users request, one way or another

**Comment by WolfieWaffle** [comment]
It is a type Ship. I just placed the ship sign on essentially a wall of three wood planks with a small wooden platform connected underneath one block into the ocean. I can try deleting my config files, perhaps that has something to do with it.

**Comment by mosemister** [comment]
Leave it for the time being. Let me attempt to recreate the issue. I may have personally changed my config and forgot to set it to default in the ships plugin, either that or because your config values are from ships 6 pre alpha 2 you may need to change a select value.

Please remeber that these ships 6 versions are all before full release, even before alpha release. So there will be bugs

**Comment by WolfieWaffle** [comment]
K, sounds good. Just wanted to make sure you have as much bug-info as possible. Keep up the good work!

**Comment by mosemister** [comment]
Found the issue, it was a mistake on my behalf. I changed some of the code around and forgot to apply it to the Ship variant, the issue will be fixed in the next update (Ships 6 preAlpha 4.1)

**Comment by WolfieWaffle** [comment]
Nice :D sounds good, I'll tell you if anything persists.

**Comment by WolfieWaffle** [comment]
Also, maybe this isn't how your code is set up, but could you use inheritance and just have all the ship variants be a child class of the ship class?

**Comment by mosemister** [comment]
It is, however due to the fact there are slight changes in the rules of the ships, the code needs to be manipulated slightly. And for the water based ships, due to the fact they move in water as well as air, the watee based ships need to allow the exepection of water and still water

**Comment by mosemister** [comment]
The new patch should be out today. With a few new features and the patch for the water ship
