### ISSUE TITLE
Feature: Ship Sinking (Most likely an addon)

### ISSUE THREAD

**Issue by WolfieWaffle** [mosemister/Ships-5-Bukkit-Version#9]
Currently I want to use this plugin over Movecraft, since it has active development and actual support. There are only two features that Movecraft has that this plugin does not, this is one of them.

In Movecraft, if you damage a ship until it cannot move any more, it will sink into the ocean. This adds a lot of immersion and I think it would be relatively easy to implement, but I'm not sure, which is why I am asking.

How possible is this to implement? Would you consider adding this feature?

**Comment by mosemister** [comment]
Yes, that feature was actually programmed into Ships 5 however never supported (you can actually see a config option for it that didnt do anything). Ships 6 has some code to support this feature however it is not a priority, but is planned to be added before full release.

**Comment by mosemister** [comment]
Its taken 2 years but this feature is now in ships 6. So im going to close the issue
